-- MySQL Script generated by MySQL Workbench
-- Sat Sep 10 19:31:57 2022
-- Model: New Model    Version: 2.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema posts_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posts_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posts_db` DEFAULT CHARACTER SET utf8mb4;
USE `posts_db`;

-- -----------------------------------------------------
-- Table `posts_db`.`POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_db`.`POST`
(
    `Id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Title`               VARCHAR(45)  NOT NULL,
    `Text`                TEXT         NULL,
    `PublicationDataTime` DATETIME     NOT NULL,
    `ChangeDateTime`      DATETIME     NULL,
    PRIMARY KEY (`Id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts_db`.`IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_db`.`IMAGE`
(
    `Id`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Hash` VARCHAR(45)  NOT NULL,
    PRIMARY KEY (`Id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts_db`.`POST_HAS_IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_db`.`POST_HAS_IMAGE`
(
    `Post`  INT UNSIGNED NOT NULL,
    `Image` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`Post`, `Image`),
    INDEX `fk_POST_HAS_IMAGE_IMAGE_idx` (`Image` ASC) VISIBLE,
    INDEX `fk_POST_HAS_IMAGE_POST_idx` (`Post` ASC) INVISIBLE,
    CONSTRAINT `fk_POST_HAS_IMAGE_POST`
        FOREIGN KEY (`Post`)
            REFERENCES `posts_db`.`POST` (`Id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_POST_HAS_IMAGE_IMAGE`
        FOREIGN KEY (`Image`)
            REFERENCES `posts_db`.`IMAGE` (`Id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


INSERT INTO `post` (`Id`, `Title`, `Text`, `PublicationDataTime`, `ChangeDateTime`)
VALUES (1, 'Сегодня я расскажу вам про тег <form></form>',
        'Тег <form> устанавливает форму на веб-странице. Форма предназначена для обмена данными между пользователем и сервером. Область применения форм не ограничена отправкой данных на сервер, с помощью клиентских скриптов можно получить доступ к любому элементу формы, изменять его и применять по своему усмотрению.\r\n\r\nДокумент может содержать любое количество форм, но одновременно на сервер может быть отправлена только одна форма. По этой причине данные форм должны быть независимы друг от друга.\r\n\r\nДля отправки формы на сервер используется кнопка Submit, того же можно добиться, если нажать клавишу Enter в пределах формы. Если кнопка Submit отсутствует в форме, клавиша Enter имитирует ее использование.\r\n\r\nКогда форма отправляется на сервер, управление данными передается программе, заданной атрибутом action тега <form>. Предварительно браузер подготавливает информацию в виде пары «имя=значение», где имя определяется атрибутом name тега <input>, а значение введено пользователем или установлено в поле формы по умолчанию. Если для отправки данных используется метод GET, то адресная строка может принимать следующий вид.\r\n\r\nhttp://www.htmlbook.ru/cgi-bin/handler.cgi?nick=%C2%E0%ED%FF+%D8%E0%EF%EE%F7%EA%E8%ED&page=5\r\n\r\nПараметры перечисляются после вопросительного знака, указанного после адреса CGI-программы и разделяются между собой символом амперсанда (&). Нелатинские символы преобразуются в шестнадцатеричное представление (в форме %HH, где HH — шестнадцатеричный код для значения ASCII-символа), пробел заменяется на плюс (+).\r\n\r\nДопускается внутрь контейнера <form> помещать другие теги, при этом сама форма никак не отображается на веб-странице, видны только ее элементы и результаты вложенных тегов.',
        '2022-09-10 19:11:49', NULL),
       (2, 'Не знаю что написать...', NULL, '2022-09-10 19:11:28', NULL),
       (3, 'Что такое Git и зачем он нужен?',
        'Git - это консольная утилита, для отслеживания и ведения истории изменения файлов, в вашем проекте. Чаще всего его используют для кода, но можно и для других файлов. Например, для картинок - полезно для дизайнеров.',
        '2022-09-10 19:12:50', NULL),
       (4, 'Сегодня день буква \"A\"!',
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
        '2022-09-10 17:16:50', '2022-09-10 17:22:23'),
       (5, 'Пример MYSQL кода.',
        'INSERT INTO `post` (`Id`, `Title`, `Text`, `PublicationDataTime`, `IsEdited`) VALUES (NULL, \'Сегодня день буква \\\"A\\\"!\', \'AAA\', \'2022-09-10 17:16:50.000000\', \'0\');',
        '2022-09-10 19:18:06', NULL),
       (6, 'Переменные в php',
        'Переменные хранят отдельные значения, которые можно использовать в выражениях PHP. Для определения переменных применяется знак доллара $. Например:\r\n\r\n$num;\r\n\r\nЗдесь определена переменная $num. Поскольку определение переменной - это отдельная инструкция, она завершается точкой с запятой.\r\nКак правило, названия переменный начинаются с маленькой буквы или символа подчеркивания. Стоит учитывать, что PHP является регистрозависимым языком, а значит, переменные $num и $Num будут представлять две разные переменные.\r\nТакже при наименовании переменных нам надо учитывать следующие правила:\r\nИмена переменных должны начинаться с алфавитного символа или с подчеркивания\r\nИмена переменных могут содержать только символы: a–z, A–Z, 0–9, и знак подчеркивания\r\nИмена переменных не должны включать в себя пробелы\r\nС помощью операции присвоения (=) переменной присваивается определенное значение:\r\n\r\n$num = 10;\r\n\r\nЗдесь определена переменная $num, которая хранит число 10.',
        '2022-09-10 19:19:28', NULL),
       (7, 'Тимофей', 'Программист на HTML. Ненавидит Assembler.', '2022-09-10 19:24:46', '2022-09-10 20:11:33');


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
