-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 16:00:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema posts_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posts_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posts_db` DEFAULT CHARACTER SET utf8mb4;
USE `posts_db`;

-- -----------------------------------------------------
-- Table `posts_db`.`POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_db`.`POST`
(
    `Id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Title`               VARCHAR(45)  NOT NULL,
    `Text`                TEXT(10000)  NULL,
    `PublicationDataTime` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts_db`.`IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_db`.`IMAGE`
(
    `Id`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Path` VARCHAR(75)  NOT NULL,
    PRIMARY KEY (`Id`),
    UNIQUE INDEX `Path_UNIQUE` (`Path` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts_db`.`POST_has_IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_db`.`POST_has_IMAGE`
(
    `Post`  INT UNSIGNED NOT NULL,
    `Image` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`Post`, `Image`),
    INDEX `fk_POST_has_IMAGE_IMAGE1_idx` (`Image` ASC) VISIBLE,
    INDEX `fk_POST_has_IMAGE_POST_idx` (`Post` ASC) VISIBLE,
    CONSTRAINT `fk_POST_has_IMAGE_POST`
        FOREIGN KEY (`Post`)
            REFERENCES `posts_db`.`POST` (`Id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_POST_has_IMAGE_IMAGE1`
        FOREIGN KEY (`Image`)
            REFERENCES `posts_db`.`IMAGE` (`Id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
