-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 16:00:28 2022
-- Model: New Model    Version: 3.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema posts_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posts_db` DEFAULT CHARACTER SET utf8mb4;
USE `posts_db`;


-- -----------------------------------------------------
-- Table USER
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS USER
(
    id                     INT                              NOT NULL AUTO_INCREMENT,
    username               VARCHAR(30)                      NOT NULL,
    email                  VARCHAR(64)                      NOT NULL UNIQUE,
    password_hash          VARCHAR(64)                      NOT NULL,
    gender                 ENUM ('male', 'female', 'other') NULL,
    registration_date_time TIMESTAMP                        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX username_idx (username ASC) VISIBLE,
    INDEX gender_idx (username ASC) VISIBLE,
    INDEX registration_date_time_idx (registration_date_time ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table POST
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS POST
(
    id                    INT         NOT NULL AUTO_INCREMENT,
    title                 VARCHAR(45) NOT NULL,
    text                  TEXT(10000) NULL,
    publication_data_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id               INT         NOT NULL,
    PRIMARY KEY (id),
    INDEX title_idx (title ASC) VISIBLE,
    INDEX publication_data_time_idx (publication_data_time ASC) VISIBLE,
    FOREIGN KEY (user_id)
        REFERENCES USER (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table IMAGE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS IMAGE
(
    id   INT         NOT NULL AUTO_INCREMENT,
    path VARCHAR(75) NOT NULL UNIQUE,
    PRIMARY KEY (id)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table POST_HAS_IMAGE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS POST_HAS_IMAGE
(
    post_id  INT NOT NULL,
    image_id INT NOT NULL,
    PRIMARY KEY (post_id, image_id),
    FOREIGN KEY (post_id)
        REFERENCES POST (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (image_id)
        REFERENCES IMAGE (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
